# Generated by Django 5.0 on 2024-06-07 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', ckeditor.fields.RichTextField()),
                ('button_title', models.CharField(max_length=255)),
            ],
        ),
    ]
