# Generated by Django 5.0 on 2024-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
