# Generated by Django 5.0 on 2024-06-09 07:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('features_lists', ckeditor.fields.RichTextField()),
                ('button_title', models.CharField(max_length=30)),
            ],
        ),
    ]
