# Generated by Django 5.0 on 2024-06-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0007_category_tag_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='blogs', to='qot_app.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='qot_app.tag'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('street_address_1', models.CharField(max_length=200)),
                ('country_of_residence', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('street_address_1', models.CharField(max_length=200)),
                ('country_of_residence', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_which_country', models.CharField(max_length=200)),
                ('education_experience', models.CharField(max_length=200)),
                ('education_background', models.CharField(max_length=200)),
                ('position_of_interest', models.CharField(max_length=200)),
                ('hear_about', models.CharField(max_length=200)),
                ('other_comments', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
