# Generated by Django 5.0 on 2024-06-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0008_alter_blog_category_alter_blog_tag_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birth_date',
        ),
    ]
