# Generated by Django 5.0 on 2024-06-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0009_remove_teacher_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='package',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='qot_app.package'),
            preserve_default=False,
        ),
    ]
