# Generated by Django 5.0 on 2024-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0010_student_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='country_of_residence',
            new_name='academic_level',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
