# Generated by Django 5.0 on 2024-06-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qot_app', '0011_rename_country_of_residence_student_academic_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='street_address_1',
        ),
    ]
